project:
  type: website
  output-dir: ../../docs/eda

website:
  title: "Fish Survey EDA"
  navbar:
    left:
      - href: eda_lpi.qmd
        text: "LPI"
      - href: eda_fish.qmd
        text: "Fish"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
